app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, BooleanField, FileField
from wtforms.validators import DataRequired, Length, Email

class NameForm(FlaskForm):
    name = StringField('What is your name?', validators=[DataRequired()])
    submit = SubmitField('Submit')

class ContactUs(FlaskForm):
    name = StringField('Name', validators=[DataRequired()], render_kw={'placeholder': 'Your Name*'})
    email = StringField('Email', validators=[DataRequired(), Email()], render_kw={'placeholder': 'Your Email*'})
    message = TextAreaField('Message', validators=[DataRequired(), Length(min=20)], render_kw={'placeholder': 'Your Message*'})
    checkbox = BooleanField('Yes, I would like to receive communications by email about octamedic services.')
    submit = SubmitField('Submit')

class EditProfileForm(FlaskForm):
    first_name = StringField('First name', validators=[Length(0, 64)])
    other_names = StringField('Other name(s)', validators=[Length(0, 64)])
    location = StringField('Location', validators=[Length(0, 64)])
    about_me = TextAreaField('About me')
    submit = SubmitField('Submit')

class PostForm(FlaskForm):
    title = StringField('Title', validators=[Length(0, 64)])
    body = TextAreaField("What's on your mind?", validators=[DataRequired()])
    submit = SubmitField('Submit')
    category = StringField('Category', validators=[Length(0, 64)])
    image = FileField('Image')

class CommentForm(FlaskForm):
    body = StringField('', validators=[DataRequired()])
    submit = SubmitField('Submit')
    

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, session, redirect, url_for, abort, request, flash, current_app, send_from_directory
from flask_login import login_required, current_user
from . import main
from .forms import ContactUs, EditProfileForm, PostForm, CommentForm
from .. import db
from ..models import User, AnatomyQuestion, PhysiologyQuestion,\
    BiochemistryQuestion, MicrobiologyQuestion, PharmacologyQuestion, ScoreTable,\
        GeneralQuestion, PathologyQuestion, Post, Permission, Comment
from flask_mail import Message
from .. import mail
import os
import random


quiz_models = {
    'anatomy': AnatomyQuestion,
    'physiology': PhysiologyQuestion,
    'biochemistry': BiochemistryQuestion,
    'microbiology': MicrobiologyQuestion,
    'pharmacology': PharmacologyQuestion,
    'general': GeneralQuestion,
    'pathology': PathologyQuestion
}

@main.route('/', methods=['GET', 'POST'])
def index():
    return render_template('main/index.html')

@main.route('/contact', methods=['GET', 'POST'])
def contact_page():
    form = ContactUs()
    if form.validate_on_submit():
        msg = Message(current_app.config['FLASKY_MAIL_SUBJECT_PREFIX'] + 'hello',
                    sender=current_app.config['FLASKY_MAIL_SENDER'], recipients=[current_app.config['MAIL_USERNAME']])
        msg.body=str(form.message.data)
        mail.send(msg)
        flash("Your Message has been delivered, Thank You!")
    return render_template('main/contact_page.html', form=form)

# @main.route('/blog')
# def blog():
#     return render_template('error/construct.html')

@main.route('/about')
def about():
    return render_template('error/construct.html')

@main.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        user = User.query.filter_by(id=session.get('user_id')).first()
        user.first_name = form.first_name.data
        user.other_names = form.other_names.data
        user.location = form.location.data
        user.about_me = form.about_me.data
        db.session.add(user)
        db.session.commit()
        flash('Your profile has been updated.')
        return redirect(url_for('main.user'))
    form.first_name.data = current_user.first_name
    form.other_names.data = current_user.other_names
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('main/edit_profile.html', form=form)

@main.route('/user/edit_post/<id>', methods=['GET', 'POST'])
def edit_post(id):
    form = PostForm()
    post = Post.query.filter_by(id=id).first()
    save_dir = '/home/abdulqudus/ALX_PROJECTS/github/Mediblitz/app/templates/static/user_images'
    if form.validate_on_submit():
        os.remove(save_dir+form.image)
        image = request.files['image']
        image_filename = image.filename
        image.save(os.path.join(save_dir, image_filename))
        post.body = form.body
        post.category = form.category
        post.headline = form.title
        post.image_path = image_filename 
        db.session.add(post)
        db.session.commit()
        flash("Your post has been updated successfully")
        return redirect('main.blog')
    form.body.data = post.body
    form.category.data = post.category
    form.title.data = post.headline
    form.image.data =  post.image_path
    return render_template('main/edit_post.html', post=post, form=form)

@main.route('/quiz_intro')
def quiz_intro():
    logged_in = session.get('user_id')
    return render_template('main/quiz_intro.html', logged_in=logged_in)

@main.route('/secret')
@login_required
def secret():
    return 'You are authorized to access this page'

@main.route('/user')
def user():
    user = User.query.filter_by(id=session.get('user_id')).first()
    if user is None:
        abort(404)
    posts_written = Post.query.filter_by(author_id=session.get('user_id')).all()
    quizzes_taken = ScoreTable.query.filter_by(user_id=session.get('user_id')).all()
    return render_template('main/user_page.html',\
                           user=user, posts_written=posts_written,\
                            quizzes_taken=quizzes_taken)

@main.route('/user_quiz', methods=['GET', 'POST'])
@login_required
def user_quiz():
    user = User.query.filter_by(id=session.get('user_id')).first()
    verified = user.is_verified
    first_name = user.first_name
    
    if user is None:
        abort(404)
    
    quizzes = {'Anatomy': url_for('main.quiz', quiz='anatomy'), 
               'Physiology': url_for('main.quiz', quiz='physiology'), 
               'Biochemistry': url_for('main.quiz', quiz='biochemistry'),
               'Pathology': url_for('main.quiz', quiz='pathology'),
               'General': url_for('main.quiz', quiz='general'),
               'Microbiology': url_for('main.quiz', quiz='microbiology'),
               'Pharmacology': url_for('main.quiz', quiz='pharmacology')
               }
    
    quiz_names = ['anatomy', 'physiology', 'biochemistry', 'pharmacology', 'microbiology', 'general', 'pathology']

    leaders = {}
    for quiz_name in quiz_names:
        leaders[quiz_name] = ScoreTable.get_top_scores(quiz_name)
    return render_template('main/quiz page.html', first_name=first_name, quizzes=quizzes, \
                           verified=verified, leaderboard=leaders, user=user)

@main.route('/user/<quiz>', methods=['GET', 'POST'])
@login_required
def quiz(quiz):

    model = quiz_models.get(quiz)
    if model:
        result = model.query.order_by(db.func.rand()).limit(20).all()
        questions_list = []
        checker_list = {}
        for question in result:
            question_dict = {
                'question_id': question.id,
                'question_text': question.question,
                'option_A': question.option_A,
                'option_B': question.option_B,
                'option_C': question.option_C,
                'option_D': question.option_D,
            }

            checker_list[question.id] = (question.question, question.answer)

            questions_list.append(question_dict)

        session['quiz_name'] = quiz
        return render_template('main/quiz.html', questions=questions_list, start=False, quiz=quiz)
    
@main.route('/user/result', methods=['GET', 'POST'])
@login_required
def result():
    quiz_name = session.get('quiz_name')
    user = User.query.filter_by(id=session.get('user_id')).first()
    
    question_ids = request.form.getlist('question_id')
    
    chosen_answers = {}
    correct_answers = {}
    for question_id in question_ids:
        answer_dict = quiz_models[quiz_name].query.filter_by(id=question_id).first()
        correct_answers[question_id] = (answer_dict.question, answer_dict.answer, answer_dict.get_answer_text())
        chosen_answer = request.form.get(f'answer_{question_id}')
        chosen_answers[question_id] = (chosen_answer, answer_dict.get_chosen_answer(chosen_answer))

    
    score = 0

    for question_id, chosen_answer in chosen_answers.items():
        if question_id in correct_answers and chosen_answer[0] == correct_answers[question_id][1]:
            score += 1
   
    total_questions = len(question_ids)
    
    try:
        percentage_score = (score / total_questions) * 100
    except:
        return redirect(url_for('main.user'))

    user_score = ScoreTable(user_id=user.id, score=percentage_score, quiz_name=session.get('quiz_name'))
    db.session.add(user_score)
    db.session.commit()

    score = percentage_score
    score_remarks = {
        (0, 12.5): "Keep going! Every step counts towards progress. You've got this!",
        (12.6, 25): "Great effort! Stay determined and you'll see improvement in no time.",
        (25.1, 37.5): "Well done! You're making strides forward. Keep up the good work!",
        (37.6, 50): "Congratulations on your progress! Your hard work is paying off. Keep pushing yourself!",
        (50.1, 62.5): "Fantastic job! You're getting closer to mastery. Keep up the excellent work!",
        (62.6, 75): "Impressive work! You're doing great. Keep challenging yourself to reach new heights!",
        (75.1, 87.5): "Outstanding performance! You're truly excelling in this area. Keep up the amazing work!",
        (87.6, 100): "Incredible achievement! You're a true expert. Keep up the exceptional work and inspire others!"
    }
    remark = next((remark for (min_score, max_score), remark in score_remarks.items() \
                   if min_score <= score <= max_score), "Invalid score")

    return render_template('main/result.html', correct_answers=correct_answers,\
                           chosen_answers=chosen_answers,\
                            percentage_score=percentage_score, remark=remark)

    
@main.route('/blog', methods=['GET', 'POST'])
def blog():
    page = request.args.get('page', 1, type=int)
    row_posts = Post.query.order_by(Post.timestamp.desc()).all()
    random.shuffle(row_posts)
    selected_posts = row_posts[:6]
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page=page, per_page=4, error_out=False)
    posts = pagination.items
    return render_template('main/blog_post.html', posts=posts, selected_posts=selected_posts, pagination=pagination)

@login_required
@main.route('/create_blog', methods=['GET', 'POST'])
def create_blog():
    form = PostForm()
    save_dir = '/home/abdulqudus/ALX_PROJECTS/github/Mediblitz/app/templates/static/user_images'
    if(request.method == 'POST'):
        if(request.files['image']):
            image = request.files['image']
            image_filename = image.filename
            image.save(os.path.join(save_dir, image_filename))
        else:
            image = 'planbg.jpg'
        post = Post(body=request.form.get('body'),
                    author=current_user._get_current_object(),
                    category=form.category.data,
                    headline=form.title.data,
                    image_path=image_filename)

app/templates/main/edit_profile.html
{% extends 'main/index.html' %}

{% block content %}
<style>
    .form-group {
    margin-bottom: 20px;
  }
  
  .form-control {
    width: 80%;
    padding: 8px;
    font-size: 16px;
    border-radius: 4px;
    border: 1px solid #ccc;
    margin-left: 20px;

  }

  .container {
    width: 70%;
    margin: auto;
    background-color: rgb(238, 236, 234);
    padding: 20px;
    border-radius: 5px;
    box-shadow: 100px;
  }
  
  .btn-primary {
    background-color: #007bff;
    color: #fff;
    padding: 10px 20px;
    border: none;
    border-radius: 4px;
    font-size: 16px;
    cursor: pointer;
  }
  
  .btn-primary:hover {
    background-color: #0056b3;
  }
  
  h2 {
    margin-top: 0;
  }
</style>
  <h2>Edit Profile</h2>
  <form class="container" method="POST" action="{{ url_for('main.edit_profile') }}">
    {{ form.hidden_tag() }}
<div>
    <div class="form-group">
      <h4>{{ form.first_name.label }} </h4>
      {{ form.first_name(class="form-control") }}
    </div>
    <div>
      <h4>{{ form.other_names.label }}</h4>
      {{ form.other_names(class="form-control") }}
    </div>
</div>
    <div class="form-group">
      <h4>{{ form.location.label }} </h4>
      {{ form.location(class="form-control") }}
    </div>
    <div class="form-group">
      <h4>{{ form.about_me.label }} </h4>
      {{ form.about_me(class="form-control", rows=5) }}
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Save Changes</button>
    </div>
  </form>

  <h3>Update Password</h3>
  <form class='container pass_form form-control' action="/auth/user/change_password" method="POST" >
  
    <div class="form-group">
        <h4><label for="current_password">Current Password</label></h4>
        <input type="password" id="current_password" name="current_password" required>
    </div>
    <div class="form-group">
        <h4><label for="new_password">New Password</label></h4>
        <input type="password" id="new_password" name="new_password" required>
    </div>
    <div class="form-group">
        <h4><label for="confirm_new_password">Confirm New Password</label></h4>
        <input type="password" id="confirm_new_password" name="confirm_new_password" required>
    </div>
    <button type="submit">Submit</button>
    
</form>
{% endblock %}

<script>
    document.addEventListener('DOMContentLoaded', function() {
var form = document.getElementsByClassName('pass_form');
var currentPasswordInput = document.getElementById('current_password');
var newPasswordInput = document.getElementById('new_password');
var confirmNewPasswordInput = document.getElementById('confirm_new_password');
var submitButton = document.querySelector('button[type="submit"]');

function validatePassword() {
var currentPassword = currentPasswordInput.value;
var newPassword = newPasswordInput.value;
var confirmNewPassword = confirmNewPasswordInput.value;

if (newPassword !== confirmNewPassword) {
  confirmNewPasswordInput.setCustomValidity('Passwords do not match');
} else {
  confirmNewPasswordInput.setCustomValidity('');
}

if (newPassword.length < 6) {
  newPasswordInput.setCustomValidity('Password must be at least 6 characters long');
} else {
  newPasswordInput.setCustomValidity('');
}
}

currentPasswordInput.addEventListener('input', validatePassword);
newPasswordInput.addEventListener('input', validatePassword);
confirmNewPasswordInput.addEventListener('input', validatePassword);

form.addEventListener('submit', function(event) {
validatePassword();

if (!form.checkValidity()) {
  event.preventDefault();
}
});
});
</script>

app/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <title>{% block title %} octamedX {% endblock %}</title>
    {% block css %} 
    <link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    {% endblock %}

    
    
</head>
<body>
    <header>
    <nav>
        <div class="nav-bar">
            <i class='bx bx-menu sidebarOpen' ></i>
            
            <span class="logo navLogo">{% block filler %}<a href="{{ url_for('main.index') }}"> octamedX </a>{% endblock %}</span>

            <div class="menu">
                <div class="logo-toggle">
                    <span class="logo"><a href="{{ url_for('main.index') }}">octamedX </a></span>
                    <i class='bx bx-x siderbarClose'></i>
                </div>

                <ul class="nav-links">
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                    <li><a href="{{ url_for('main.about') }}">About</a></li>
                    {% if not current_user.is_authenticated %}
                    <li><a href="{{ url_for( 'auth.login') }}">Login or Register</a></li>
                    {% else %}
                    <li><a href="{{ url_for( 'main.user') }}">Dashboard</a></li>
                    {% endif %}
                    <li><a href="{{ url_for('main.blog') }}">Blog</a></li>
                    <li><a href="{{ url_for( 'main.contact_page') }}">Contact</a></li>
                </ul>
            </div>

            <div class="darkLight-searchBox">
                <div class="dark-light">
                    <i class='bx bx-moon moon'></i>
                    <i class='bx bx-sun sun'></i>
                </div>

                <div class="searchBox">
                   <div class="searchToggle">
                    </div>
                    <div class="search-field">
                    </div>
                </div>
            </div>
        </div>
    </nav>

    
    </header>
    <div class="flash-messages" id="flash-messages">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul class="flash-messages-list">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
    </div>
    {% block content %}
    <article>
    <h1>The Intersection of Health and Technology: Transforming the Future of Healthcare</h1>
    <div class="image-container">
        <img src="static/images/MIT-Healthcare-Technology-01_0.jpg" alt="Healthcare Technology">
    </div>
    <p>
        In recent years, the convergence of health and technology has revolutionized the healthcare industry, paving the way for transformative advancements and improved patient outcomes.
        The integration of cutting-edge technologies into healthcare systems has ushered in an era of personalized medicine, remote patient monitoring, enhanced diagnostics, and streamlined healthcare delivery.
        Let us explore the profound impact of this intersection and how it is shaping the future of healthcare.
    </p>

    <div class="section">
        <h2 class="section-title">Enhanced Diagnostics</h2>
        <p class="section-content">
            One of the significant benefits of the intersection of health and technology is the development of advanced diagnostic tools.
            From artificial intelligence (AI) algorithms capable of analyzing medical images and detecting anomalies with remarkable accuracy to wearable devices that monitor vital signs in real-time, technology has empowered healthcare professionals with unprecedented diagnostic capabilities.
            These tools not only expedite the diagnosis process but also enhance accuracy, leading to early detection of diseases and more effective treatment plans.
        </p>
    </div>

    <div class="section">
        <h2 class="section-title">Telemedicine and Remote Monitoring</h2>
        <div class="image-container">
            <img src="static/images/telemedicine.webp" alt="Healthcare Technology">
        </div>
        <p class="section-content">
            Technology has bridged the gap between patients and healthcare providers, particularly through telemedicine and remote monitoring solutions.
            Telemedicine enables patients to consult with healthcare professionals from the comfort of their homes, eliminating the need for physical visits and reducing healthcare costs.
            Moreover, remote monitoring devices allow continuous tracking of patients' health parameters, such as blood pressure, glucose levels, and heart rate.
            This real-time data empowers physicians to monitor patients' conditions remotely, provide timely interventions, and prevent complications.
        </p>
    </div>

    <div class="section">
        <h2 class="section-title">Patient Empowerment</h2>
        <p class="section-content">
            The intersection of health and technology has shifted the dynamics of patient care, placing greater emphasis on patient empowerment.
            With the advent of health-related mobile applications and wearable devices, individuals can actively participate in managing their health.
            These tools provide access to personalized health information, fitness tracking, medication reminders, and health education resources.
            By promoting self-care and preventive measures, technology empowers individuals to take control of their well-being, leading to improved health outcomes and reduced healthcare burdens.
        </p>
    </div>

    <div class="section">
        <h2 class="section-title">Big Data and AI in Healthcare</h2>
        <p class="section-content">
            The abundance of health-related data generated daily has given rise to the use of big data analytics and AI in healthcare.
            By analyzing vast amounts of patient data, such as electronic health records and clinical trial results, AI algorithms can identify patterns, predict disease progression, and facilitate personalized treatment plans.
            Furthermore, AI-powered chatbots and virtual assistants enable patients to receive instant medical advice and support, enhancing access to healthcare services and reducing waiting times.
        </p>
    </div>

    <div class="section">
        <h2 class="section-title">Challenges and Ethical Considerations</h2>
        <p class="section-content">
            While the intersection of health and technology brings immense opportunities, it also presents challenges and ethical considerations.
            Privacy and data security, interoperability of systems, and ensuring equitable access to technology are crucial areas that require attention.
            Striking a balance between technological advancements and maintaining the human touch in healthcare is another critical aspect to consider.
        </p>
    </div>

    <p class="conclusion">
        The intersection of health and technology has the potential to transform the future of healthcare, empowering patients, improving diagnostics, and revolutionizing healthcare delivery.
        As technology continues to evolve, it is imperative for healthcare professionals, policymakers, and stakeholders to embrace these advancements responsibly, ensuring that patient-centered care and ethical considerations remain at the forefront.
        By harnessing the power of technology, we can createa future where healthcare is more accessible, personalized, and effective, ultimately improving the well-being of individuals and communities worldwide.
    </p>
    </article>
    <footer class="footer"><small>© 2025 octamedx</small></footer>
    {% endblock %}
{% block script %}
<script>
    const body = document.querySelector("body"),
          nav = document.querySelector("nav"),
          modeToggle = document.querySelector(".dark-light"),
          searchToggle = document.querySelector(".searchToggle"),
          sidebarOpen = document.querySelector(".sidebarOpen"),
          siderbarClose = document.querySelector(".siderbarClose");
    
          let getMode = localStorage.getItem("mode");
              if(getMode && getMode === "dark-mode"){
                body.classList.add("dark");
              }
    
    // js code to toggle dark and light mode
          modeToggle.addEventListener("click" , () =>{
            modeToggle.classList.toggle("active");
            body.classList.toggle("dark");
    
            // js code to keep user selected mode even page refresh or file reopen
            if(!body.classList.contains("dark")){
                localStorage.setItem("mode" , "light-mode");
            }else{
                localStorage.setItem("mode" , "dark-mode");
            }
          });
    
    // js code to toggle search box
            searchToggle.addEventListener("click" , () =>{
            searchToggle.classList.toggle("active");
          });
     
          
    sidebarOpen.addEventListener("click" , () =>{
        nav.classList.add("active");
    });
    
    body.addEventListener("click" , e =>{
        let clickedElm = e.target;
    
        if(!clickedElm.classList.contains("sidebarOpen") && !clickedElm.classList.contains("menu")){
            nav.classList.remove("active");
        }
    });
    setTimeout(function() {
                var flashMessages = document.getElementById('flash-messages');
                if (flashMessages) {
                    flashMessages.remove();
                }
            }, 5000);
    </script>
{% endblock %}
</body>
</html>

app/templates/main/quiz.html
{% extends 'main/index.html' %}
    {% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='quiz.css') }}">
    {% endblock %}    

<body>
    {% block content %}
    <h1 style="text-transform: capitalize;">{{ quiz }} Quiz </h1>

    {% if questions %}
        <div id="startBtnContainer">
            <h3>Instructions:</h3>
            <p><ul class="li-des" >
                <li>Read each question carefully and select the correct answer</li> 
                <li>Each question will be displayed for <strong> 20 seconds</strong></li>
                </ul>
                <br> Click the "Start" button when you're ready to begin.
            </p>
            <button id="startBtn" onclick="startQuiz();">Start</button>
        </div>
    <form id="quizForm" method="post" action="{{ url_for('main.result', email=email) }}" onsubmit="submitForm()">
        <div id="questionContainer" style="display: none;">
            <div class="timer" id="timer"></div>

            {% for question in questions %}
                <div class="question no-select" style="display: none;">
                    <h3 class="question-no">Question {{ loop.index }}:</h3>
                    <p class="question-question">{{ question.question_text }}</p>
                    <ul>
                        <input type="hidden" name="question_id" value="{{ question.question_id }}">
                        <li>
                            <input type="radio" id="answer_{{ question.question_id }}_A" name="answer_{{ question.question_id }}" value="A">
                            <label for="answer_{{ question.question_id }}_A">{{ question.option_A }}</label>
                        </li>
                        <li>
                            <input type="radio" id="answer_{{ question.question_id }}_B" name="answer_{{ question.question_id }}" value="B">
                            <label for="answer_{{ question.question_id }}_B">{{ question.option_B }}</label>
                        </li>
                        <li>
                            <input type="radio" id="answer_{{ question.question_id }}_C" name="answer_{{ question.question_id }}" value="C">
                            <label for="answer_{{ question.question_id }}_C">{{ question.option_C }}</label>
                        </li>
                        <li>
                            <input type="radio" id="answer_{{ question.question_id }}_D" name="answer_{{ question.question_id }}" value="D">
                            <label for="answer_{{ question.question_id }}_D">{{ question.option_D }}</label>
                        </li>
                    </ul>
                </div>
            {% endfor %}

            <button type="button" id="nextBtn" onclick="nextQuestion();">Next</button>
            <button type="button" id="submitBtn" onclick="submitForm();" style="display: none;">Submit</button>
        </div>
    </form>
    {% endif %}
    {% endblock %}
    {% block script %}
    {{ super() }}
    <script>
        var timeLeft = 20; // Time in seconds
        var timerId;
        var questionIndex = 0; // Index of the current question
    
        function startQuiz() {
            document.getElementById('startBtn').style.display = 'none'; // Hide the start button
            document.getElementById('startBtnContainer').style.display = 'none'; // Hide the instruction page
            document.getElementById('questionContainer').style.display = 'block'; // Show the question container
            displayQuestion(); // Display the first question
            startTimer(); // Start the timer
        }
    
        function startTimer() {
            timerId = setInterval(countdown, 1000);
        }
    
        function countdown() {
            if (timeLeft === 0) {
                clearInterval(timerId);
                if (questionIndex === 19 ) {
                    submitForm(); // Trigger the form submission if it's the last question
                } else {
                    nextQuestion(); // Move to the next question when the time runs out
                }
            } else {
                document.getElementById("timer").textContent = "Time Left: " + timeLeft + "s";
                timeLeft--;
            }
        }
    
        function displayQuestion() {
            var questions = document.getElementsByClassName("question");
            for (var i = 0; i < questions.length; i++) {
                questions[i].style.display = "none"; // Hide all questions
            }
            questions[questionIndex].style.display = "block"; // Show the current question
        }
    
        function nextQuestion() {
            clearInterval(timerId); // Stop the timer
            questionIndex++; // Move to the next question
            if (questionIndex < {{ questions|length }} ) {
                timeLeft = 20; // Reset the timer for the next question
                displayQuestion(); // Display the next question
                startTimer(); // Start the timer
            } else {
                showSubmitButton(); // Show the submit button if all questions have been answered
            }
        }
    
        
        function showSubmitButton() {
            document.getElementById("nextBtn").style.display = "none"; // Hide the next button
            document.getElementById("submitBtn").style.display = "block"; // Show the submit button
        }
    
        function submitForm() {
            clearInterval(timerId); // Stop the timer
            // Replace the current URL with the user dashboard page URL
            var dashboardUrl = "{{ url_for('main.user') }}";
            window.location.replace(dashboardUrl);
            // Submit the form
            document.getElementById("quizForm").submit();
        } 
    
        window.addEventListener("DOMContentLoaded", function() {
            // Get all the question elements
            var questionElements = document.querySelectorAll(".question");
    
            // Loop through each question element and disable text selection and context menu
            questionElements.forEach(function(questionElement) {
                questionElement.classList.add("no-select");
                questionElement.addEventListener("contextmenu", function(event) {
                    event.preventDefault();
                });
            });
        });
        
    </script>
    
    {% endblock %}
</body>